-- Add comprehensive business information columns to clients table
ALTER TABLE clients 
ADD COLUMN IF NOT EXISTS business_address TEXT,
ADD COLUMN IF NOT EXISTS business_website VARCHAR,
ADD COLUMN IF NOT EXISTS contact_person_name VARCHAR,
ADD COLUMN IF NOT EXISTS contact_person_role VARCHAR,
ADD COLUMN IF NOT EXISTS contact_person_phone VARCHAR,
ADD COLUMN IF NOT EXISTS contact_person_email VARCHAR,
ADD COLUMN IF NOT EXISTS products_services JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS pricing_information JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS return_policy TEXT,
ADD COLUMN IF NOT EXISTS payment_methods JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS business_hours JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS insurance_accepted JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS specialties JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS certifications JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS service_areas JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS business_documents JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS business_images JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS logo_url VARCHAR,
ADD COLUMN IF NOT EXISTS common_questions JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS appointment_types JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS staff_information JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS promotional_content TEXT,
ADD COLUMN IF NOT EXISTS compliance_notes TEXT;